$("#home").click(function(){
  $("#homeContent").addClass("hide");
  $("#home").removeClass("active");
  $("#searchContent").addClass("hide");
  $("#search").removeClass("active");
  $("#aboutContent").addClass("hide");
  $("#about").removeClass("active");
  $("#homeContent").removeClass("hide");
  $("#home").addClass("active");
});

$("#search").click(function(){
  $("#homeContent").addClass("hide");
  $("#home").removeClass("active");
  $("#searchContent").addClass("hide");
  $("#search").removeClass("active");
  $("#aboutContent").addClass("hide");
  $("#about").removeClass("active");
  $("#searchContent").removeClass("hide");
  $("#search").addClass("active");
});

$("#about").click(function(){
  $("#homeContent").addClass("hide");
  $("#home").removeClass("active");
  $("#searchContent").addClass("hide");
  $("#search").removeClass("active");
  $("#aboutContent").addClass("hide");
  $("#about").removeClass("active");
  $("#aboutContent").removeClass("hide");
  $("#about").addClass("active");
});
